### ISSUE TITLE
rules_android is at failing at head (using last released Bazel)

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_android#134] opened 2023-09-12 06:07 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3301#018a8729-3a82-4f9d-94ad-55c9bba5ad9d

Platform : Macos, Ubunut, Windows

Logs
```
 ERROR: /private/var/tmp/_bazel_buildkite/c20264bbc759d5aac7fdbed934c4ab01/external/io_bazel_rules_go/go/private/context.bzl:556:23: Use of Starlark transition without allowlist attribute '_allowlist_function_transition'. See Starlark transitions documentation for details and usage: @io_bazel_rules_go//go/private:context.bzl NORMAL
(04:18:43) ERROR: Skipping '//src/...': error loading package under directory 'src': error loading package 'src/tools/bundletool_module_builder': at /private/var/tmp/_bazel_buildkite/c20264bbc759d5aac7fdbed934c4ab01/external/io_bazel_rules_go/go/def.bzl:26:5: initialization of module 'go/private/context.bzl' failed
(04:18:43) ERROR: error loading package under directory 'src': error loading package 'src/tools/bundletool_module_builder': at /private/var/tmp/_bazel_buildkite/c20264bbc759d5aac7fdbed934c4ab01/external/io_bazel_rules_go/go/def.bzl:26:5: initialization of module 'go/private/context.bzl' failed
```

Steps:
```
git clone https://github.com/bazelbuild/rules_android.git && cd rules_android
git reset 7760d83db7e57961b2d865f75788b3b5f5db6ab8 --hard
export USE_BAZEL_VERSION=07e0d316a345a3cb2593f98525320590bbc56e30
bazel build //src/... //test/... //android/... //rules/... -//src/java/com/example/sampleapp/... //toolchains/... //tools/... -//tools/android/...
```
Culprit : https://github.com/bazelbuild/bazel/commit/10a46b1e85f0b5bf8564c125dd02cd4e70017452

CC Greenteam @meteorcloudy

**Comment by comius** [comment] 2023-09-12 06:14
The problem is stale version of rules_go in rules_android.
The version of rules_go is upgraded in rules_android at head, however rules_android build at head is failing (downstream is using last green).

**Comment by comius** [comment] 2023-09-12 06:24
cc @katre @timpeut

**Comment by comius** [comment] 2023-09-12 06:25
cc @lucasvtenorio

**Comment by katre** [comment] 2023-09-12 13:08
Looks like several sets of failures:
- `extra_args[@]: unbound variable` - macOS intel
- `bazelisk: cannot execute binary file` - macOS arm
  - This is https://github.com/bazel-contrib/rules_bazel_integration_test/issues/194, will be fixed by https://github.com/bazel-contrib/rules_bazel_integration_test/pull/202, once that's in I'll update
- `no such target '@rules_jvm_external~4.5~maven~rules_android_maven//:androidx_privacysandbox_tools_tools_apigenerator':` - bzlmod

I'll take a look at the `extra_args` issue, that might be due to the version of bash being used on macOS. I can also loom at the maven issue with bzlmod, probably just something was only added to the WORKSPACE and not to MODULE.bzl.

**Comment by katre** [comment] 2023-09-12 20:17
All issues resolved: https://buildkite.com/bazel/rules-android/builds/1823

**Comment by katre** [comment] 2023-09-12 20:17
(I;d close this but I don't have permissions)

**Comment by ahumesky** [comment] 2023-09-12 20:25
Thanks all!

**Closed by ahumesky** 2023-09-12 20:25 UTC
